---
- name: Load Section 6 controls
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/logging_auditing.yml"
  tags: [section_6]

- name: Section 6 automated controls
  ansible.builtin.include_tasks: audit_shell_control.yml
  loop: "{{ cis_section6_controls }}"
  loop_control:
    loop_var: cis_control
    label: "{{ cis_control.id }} {{ cis_control.title }}"
  when: (cis_control.profiles | intersect(cis_effective_profiles) | length) > 0
  tags: [section_6]

- name: Section 6 manual controls
  ansible.builtin.include_tasks: audit_manual_control.yml
  loop: "{{ cis_section6_manual_controls }}"
  loop_control:
    loop_var: cis_control
    label: "{{ cis_control.id }} {{ cis_control.title }}"
  when: (cis_control.profiles | intersect(cis_effective_profiles) | length) > 0
  tags: [section_6]
