[debian13]
server1 ansible_host=192.0.2.10

[debian13:vars]
ansible_user=audituser
ansible_password=CHANGE_ME

ansible_become=true
ansible_become_method=su
ansible_become_user=root
ansible_become_password=CHANGE_ME

ansible_python_interpreter=/usr/bin/python3
