[debian13]
server1 ansible_host=192.168.1.10
server2 ansible_host=192.168.1.11

[debian13:vars]
ansible_user=mysshuser
ansible_password=MySSHPassword

ansible_become=true
ansible_become_method=sudo
ansible_become_user=root
ansible_become_password=MyRootPassword

ansible_python_interpreter=/usr/bin/python3
